Add support for AEPEX
daniestevez/gr-satellites pull request #675
Opened 2024-10-24 20:53 UTC by git-addrian

Per discussion [here](https://github.com/daniestevez/gr-satellites/discussions/673), adding gr-satellites support for the Atmospheric Effects of Precipitation through Energetic X-Rays (AEPEX) mission. The decoder created is for 70cm telemetry.

2024-10-25 06:57 UTC, daniestevez requested changes
Thanks for submitting this PR. I have a few comments about coding style.

2024-10-25 06:57 UTC, daniestevez commented on python/telemetry/aepex_sw_stat.py
> +    'sw_eps_pwr_state_inst4' / Enum(BitsInteger(1), OFF=0, ON=1),
Same remark regarding code repetition.

2024-10-25 06:57 UTC, daniestevez commented on python/telemetry/aepex_sw_stat.py
> +sw_ana = BitStruct(
`LinearAdapter` or `AffineAdapter` is suitable for many of these. A variable can be defined for the adapters of several fields that use the same coefficients (example: `PolynomialAdapter([0.000000e+00, 8.056600e-04], BitsInteger(16))`).

2024-10-25 06:57 UTC, daniestevez commented on python/telemetry/aepex_sw_stat.py
> +sw_adcs = BitStruct(
Same comment about code repetition and adapters.

2024-10-29 19:21 UTC, git-addrian commented
Hey @daniestevez , I have made the requested changes. Some notes:

- In order to use LinearAdapter or AffineAdapter, I had to modify the coefficients. For example, if a previous version used PolynomialAdapter([0.0, c1], BitsInteger(8)), it had to be updated to be LinearAdapter(1/c1, BitsInteger(8)). I have gone through and updated each one to reflect it. 
- Packets without APID 0x01 are now handled by GreedyBytes. APID 0x01 is the packet that will beacon. At this time we do not intend to create a decoder for other APIDs. 
- Other feedback has been incorporated!

Best,
Adrian

2024-10-29 19:31 UTC, daniestevez commented
Thanks @git-addrian! The code looks good now. However CI is failing. The error is [ModuleNotFoundError: No module named 'satellites'](https://github.com/daniestevez/gr-satellites/actions/runs/11580821781/job/32240195708?pr=675#step:4:513). Sometimes I've seen Python errors in the `satellites` module cause this `ModuleNotFoundError` because of how it is imported within a `try` statement. The real error gets eaten up, which doesn't make the cause obvious.

Can you take at look at this? If this is working fine for you locally, I can take a look too. Maybe the CI pipeline is broken and would also fail for the `main` branch.

2024-10-29 19:38 UTC, daniestevez commented
I found the problem by building locally and importing the `python` module from the `build` directory:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daniel/gr-satellites/python/__init__.py", line 54, in <module>
    from .adsb_kml import adsb_kml
  File "/home/daniel/gr-satellites/python/adsb_kml.py", line 15, in <module>
    from .telemetry import gomx_3 as tlm
  File "/home/daniel/gr-satellites/python/telemetry/__init__.py", line 22, in <module>
    from .aepex_70cm import aepex_70cm
  File "/home/daniel/gr-satellites/python/telemetry/aepex_70cm.py", line 18, in <module>
    from .aepex_sw_stat import aepex_sw_stat
  File "/home/daniel/gr-satellites/python/telemetry/aepex_sw_stat.py", line 13, in <module>
    from .adapters import PolynomialAdapter, LinearAdapter
ModuleNotFoundError: No module named 'python.telemetry.adapters'
```

The problem is that this line
```python
from .adapters import PolynomialAdapter, LinearAdapter
```
should say
```python
from ..adapters import PolynomialAdapter, LinearAdapter
```

Can you fix this and test locally that the telemetry parser runs correctly afterwards (since there are no unit tests for it)?

2024-10-30 03:55 UTC, git-addrian commented
Hey @daniestevez ,
I was able to fix that line, build it, and confirm it was working with some different test telemetry. I also fixed the following:

- AEPEX.yml was not pointing to its decoder, 'aepex_70cm'. This was silly, and was causing most of my issues with the local build.
- I recieved corrections on which telemetry was supposed to be signed instead of unsigned. Some telemetry readings are now much more accurate.

Please let me know if there are any other changes to be made!

2024-10-30 08:00 UTC, daniestevez commented
> AEPEX.yml was not pointing to its decoder, 'aepex_70cm'.

Good point. I didn't notice this.

2024-10-30 08:00 UTC, daniestevez approved these changes
Everything looks good now! Merging.

2024-10-30 08:01 UTC, merged